name: Deploy Docusaurus to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Build Docusaurus project
              run: bun run build -- --no-ssr

            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: ./build

    deploy:
        runs-on: ubuntu-latest
        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        needs: build

        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
